-- -- DELETE FROM ctr_campos;
-- ctr_campos;

-- Módulo Administrativo (3)

-- DELETE FROM ctr_campos;

INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 1,  'Nome do paciente',      '$paciente',                3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 1);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 2,  'CPF do paciente',       '$cpfPaciente',             3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 2);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 3,  'RG do paciente',        '$rgPaciente',              3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 3);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 4,  'Nome do responsável',   '$responsavel',             3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 4);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 5,  'CPF do responsável',    '$cpfResponsavel',          3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 5);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 6,  'RG do responsável',     '$rgResponsavel',           3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 6);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 7,  'Curso',                 '$curso',                   3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 7);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 8,  'Dia da semana',         '$diaSemana',               3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 8);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 9,  'Data inicial',          '$dataInicial',             3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 9);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 10, 'Data final',            '$dataFinal',               3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 10);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 11, 'Data por extenso',      '$dataExtenso',             3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 11);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 12, 'Valor da parcela',      '$valorParcela',            3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 12);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 13, 'Número de Parcelas',    '$parcelas',                3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 13);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 14, 'Dia Vencimento',        '$diaVencimento',           3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 14);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 15, 'Valor até o vencimento','$valorAteVencimento',      3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 15);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 16, 'Hora inicial',          '$horaInicial',             3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 16);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 17, 'Hora final',            '$horaFinal',               3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 17);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 18, 'Valor total',           '$valorTotal',              3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 18);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 19, 'Taxa',                  '$taxa',                    3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 19);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 20, 'Contrato',              '$contrato',                3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 20);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 21, 'Ano',                   '$ano',                     3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 21);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 22, 'Endereço paciente',     '$enderecoPaciente',        3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 22);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 23, 'Bairro paciente',       '$bairroPaciente',          3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 23);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 24, 'Cidade paciente',       '$cidadePaciente',          3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 24);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 25, 'Estado paciente',       '$estadoPaciente',          3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 25);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 26, 'CEP paciente',          '$cepPaciente',             3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 26);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 27, 'E-mail paciente',       '$emailPaciente',           3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 27);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 28, 'Nascimento paciente',   '$pacienteDataNascimento',  3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 28);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 29, 'Endereço responsável',  '$enderecoResponsavel', 3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 29);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 30, 'Bairro responsavel',    '$bairroResponsavel',   3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 30);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 31, 'Cidade responsavel',    '$cidadeResponsavel',   3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 31);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 32, 'Estado responsavel',    '$estadoResponsavel',   3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 32);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 33, 'CEP responsavel',       '$cepResponsavel',      3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 33);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 34, 'Data inicial extenso',  '$dataInicialExtenso',  3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 34);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 35, 'Data final extenso',    '$dataFinalExtenso',    3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 35);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 36, 'Meses',                 '$meses',               3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 36);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 37, 'Meses extenso',         '$mesesExtenso',        3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 37);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 38, 'Descrição',             '$descricao',           3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 38);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 39, 'Nascimento paciente',   '$nascimentoPaciente',  3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 39);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 40, 'Lista valores',         '$listaValores',        3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 40);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 41, 'Lista valores com data','$listaValoresComData', 3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 41);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 42, 'E-mail responsável',    '$emailResponsavel',    3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 42);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 43, 'Telefones Responsável', '$telefonesResponsavel',3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 43);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 44, 'Telefones Paciente',            '$telefonesPaciente',           3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 44);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 45, 'Estado Cívil Responsável',      '$estadoCivilResponsavel',      3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 45);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 46, 'Estado Cívil Paciente',         '$estadoCivilPaciente',         3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 46);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 47, 'Local trabalho paciente',       '$localTrabalhoPaciente',       3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 47);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 48, 'Local trabalho responsável',    '$localTrabalhoResponsavel',    3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 48);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 49, 'Data do vencimento da parcela', '$vencimentoParcela',           3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 49);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 50, 'Desconto',                      '$desconto',                    3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 50);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 51, 'Desconto por extenso',          '$descontoExtenso',             3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 51);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 52, 'Mes/Ano Inicial Extenso',       '$mesAnoInicalExtenso',         3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 52);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 53, 'Mes/Ano Final   Extenso',       '$mesAnoFinalExtenso',          3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 53);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 54, 'Sala',                          '$sala',                        3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 54);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 55, 'Data Emissão',                  '$dataEmissao',                 3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 55);
INSERT INTO ctr_campos (id, ds_campo, ds_variavel, id_modulo) SELECT 56, 'Valor Entrada',                 '$valorEntrada',                3 WHERE NOT EXISTS ( SELECT id FROM ctr_campos WHERE id = 56);
SELECT setval('ctr_campos_id_seq', max(id)) FROM ctr_campos;
